require_relative '../app/employee.rb'
require_relative '../app/product.rb'
require_relative '../app/startup.rb'
require_relative '../tinyGameEngine/UI.rb'
require_relative '../tinyGameEngine/gameevent.rb'
require_relative '../app/tech_name_generator.rb'
require_relative '../tinyGameEngine/gametrigger.rb'
include NamesVariables
include NamesVariablesMenWomen
include ProductNameVariables
require 'pry'
require 'colorize'